// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzSY5jNCXRVnr-WVI9Y5b7GCdIh3F3M-k',
    appId: '1:560356401180:web:0088cbc820abe855f0ffd9',
    messagingSenderId: '560356401180',
    projectId: 'popmedia-38845',
    authDomain: 'popmedia-38845.firebaseapp.com',
    storageBucket: 'popmedia-38845.firebasestorage.app',
    measurementId: 'G-6PJGYQSCW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhvqxcWqVXHbTuSdEgtOv8opnd3tCClo',
    appId: '1:560356401180:android:7ce6b7c0fb78afc1f0ffd9',
    messagingSenderId: '560356401180',
    projectId: 'popmedia-38845',
    storageBucket: 'popmedia-38845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZmcGdWsMRpYMjq3V8HqIWiSwNcw1AZ0',
    appId: '1:560356401180:ios:a38bd00c4041e9aff0ffd9',
    messagingSenderId: '560356401180',
    projectId: 'popmedia-38845',
    storageBucket: 'popmedia-38845.firebasestorage.app',
    iosBundleId: 'com.example.popMedia',
  );
}
